import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Calculator App",
  description: "Generated by create next app",
};

import { ToastContainer } from "react-toastify";

// import 'react-toastify/dist/ReactToastify.css';
// minified version is also included
import "react-toastify/dist/ReactToastify.min.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
